//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.05 at 11:16:56 AM EST 
//


package backend;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for type-question complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="type-question">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="caption" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="shortName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;element name="text" type="{}type-text"/>
 *           &lt;element name="check" type="{}type-check"/>
 *           &lt;element name="radio" type="{}type-radio"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "type-question", propOrder = {
    "captionAndShortNameAndText"
})
public class TypeQuestion {

    @XmlElementRefs({
        @XmlElementRef(name = "radio", type = JAXBElement.class),
        @XmlElementRef(name = "text", type = JAXBElement.class),
        @XmlElementRef(name = "caption", type = JAXBElement.class),
        @XmlElementRef(name = "check", type = JAXBElement.class),
        @XmlElementRef(name = "shortName", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> captionAndShortNameAndText;

    /**
     * Gets the value of the captionAndShortNameAndText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the captionAndShortNameAndText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCaptionAndShortNameAndText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link TypeCheck }{@code >}
     * {@link JAXBElement }{@code <}{@link TypeRadio }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TypeText }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getCaptionAndShortNameAndText() {
        if (captionAndShortNameAndText == null) {
            captionAndShortNameAndText = new ArrayList<JAXBElement<?>>();
        }
        return this.captionAndShortNameAndText;
    }

}
